coverage:
  status:
    project:
      default:
        target: 50% # Desired target
        threshold: 5% # Allow coverage to drop by 5% and still pass
    patch:
      default:
        target: 80% # Target for new code in the PR
